// Code generated by protoc-gen-go.
// source: auth/auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth/auth.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Ip       string `protobuf:"bytes,3,opt,name=ip" json:"ip,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type LoginResponse struct {
	Token      string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Time       string `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
	LoginTimes int64  `protobuf:"varint,3,opt,name=login_times,json=loginTimes" json:"login_times,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *LoginResponse) GetLoginTimes() int64 {
	if m != nil {
		return m.LoginTimes
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/auth.Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4f, 0x87, 0x30,
	0x10, 0xc5, 0x85, 0x2f, 0x18, 0x38, 0x7f, 0x25, 0xa7, 0x89, 0x84, 0x45, 0xc3, 0xe4, 0x84, 0x09,
	0x6e, 0x6e, 0x32, 0x3b, 0x10, 0x62, 0x1c, 0x5c, 0x0c, 0x86, 0x2a, 0x8d, 0xd2, 0x56, 0xae, 0x8d,
	0xff, 0xbe, 0xb9, 0x03, 0x8d, 0x2e, 0xcd, 0xbd, 0xf7, 0xd2, 0x4f, 0x7b, 0x0f, 0x4e, 0x86, 0xe0,
	0xa7, 0x6b, 0x3e, 0x6a, 0xb7, 0x58, 0x6f, 0x31, 0xe1, 0xb9, 0x7a, 0x84, 0xc3, 0x7b, 0xfb, 0xa6,
	0x4d, 0xaf, 0x3e, 0x83, 0x22, 0x8f, 0x25, 0x64, 0x81, 0xd4, 0x62, 0x86, 0x59, 0x15, 0xd1, 0x65,
	0x74, 0x95, 0xf7, 0xbf, 0x9a, 0x33, 0x37, 0x10, 0x7d, 0xd9, 0x65, 0x2c, 0xe2, 0x35, 0xfb, 0xd1,
	0x78, 0x0c, 0xb1, 0x76, 0xc5, 0x4e, 0xdc, 0x58, 0xbb, 0xea, 0x09, 0x8e, 0x36, 0x2e, 0x39, 0x6b,
	0x48, 0xe1, 0x19, 0xa4, 0xde, 0xbe, 0x2b, 0xb3, 0x51, 0x57, 0x81, 0x08, 0x89, 0xd7, 0xb3, 0xda,
	0x70, 0x32, 0xe3, 0x05, 0x1c, 0x7c, 0xf0, 0xd5, 0x67, 0x56, 0x24, 0xcc, 0x5d, 0x0f, 0x62, 0x3d,
	0xb0, 0xd3, 0xdc, 0x42, 0x72, 0x17, 0xfc, 0x84, 0x0d, 0xa4, 0xf2, 0x06, 0x62, 0x2d, 0x7b, 0xfd,
	0x5d, 0xa4, 0x3c, 0xfd, 0xe7, 0xad, 0x9f, 0xa8, 0xf6, 0xda, 0x73, 0xc8, 0xc6, 0x57, 0x92, 0xac,
	0xcd, 0x99, 0xd2, 0x71, 0x19, 0x5d, 0xf4, 0xb2, 0x2f, 0xad, 0xdc, 0x7c, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x83, 0x1e, 0x34, 0x81, 0x28, 0x01, 0x00, 0x00,
}
