// Code generated by protoc-gen-go.
// source: errors.proto
// DO NOT EDIT!

/*
Package file is a generated protocol buffer package.

It is generated from these files:
	errors.proto
	file.proto

It has these top-level messages:
	FileSystemError
	FileStore
	FileStoreURL
	FileStoreExtra
	Path
	File
	FileBlock
	Token
	ListResponse
	CopyRequest
	CopyResponse
	MoveRequest
	MoveResponse
	DeleteResponse
	CreateDirectoryResponse
	CreateFileMetaResponse
	GetFileMetaResponse
	PutFileResponse
	GetFileRequest
	ControlledPacket
*/
package file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileSystemError_FileSystemErrorStatus int32

const (
	FileSystemError_ACCESS_DENIED       FileSystemError_FileSystemErrorStatus = 0
	FileSystemError_DIRECTORY_NOT_EMPTY FileSystemError_FileSystemErrorStatus = 1
	FileSystemError_FILE_ALREADY_EXSITS FileSystemError_FileSystemErrorStatus = 2
	FileSystemError_INVALID_PATH        FileSystemError_FileSystemErrorStatus = 3
	FileSystemError_NO_SUCH_FILE        FileSystemError_FileSystemErrorStatus = 4
	FileSystemError_NOT_DIRECTORY       FileSystemError_FileSystemErrorStatus = 5
)

var FileSystemError_FileSystemErrorStatus_name = map[int32]string{
	0: "ACCESS_DENIED",
	1: "DIRECTORY_NOT_EMPTY",
	2: "FILE_ALREADY_EXSITS",
	3: "INVALID_PATH",
	4: "NO_SUCH_FILE",
	5: "NOT_DIRECTORY",
}
var FileSystemError_FileSystemErrorStatus_value = map[string]int32{
	"ACCESS_DENIED":       0,
	"DIRECTORY_NOT_EMPTY": 1,
	"FILE_ALREADY_EXSITS": 2,
	"INVALID_PATH":        3,
	"NO_SUCH_FILE":        4,
	"NOT_DIRECTORY":       5,
}

func (x FileSystemError_FileSystemErrorStatus) String() string {
	return proto.EnumName(FileSystemError_FileSystemErrorStatus_name, int32(x))
}
func (FileSystemError_FileSystemErrorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

// FileSystemError is a message that giving details of errors occurs when
// requests are handled by server. FileSystemError should be returned with
// operation response.
//
// Status should be one of the one of the FileSystemErrorStatus.
// Error message should be detailed message that explains what happened.
type FileSystemError struct {
	Status       FileSystemError_FileSystemErrorStatus `protobuf:"varint,1,opt,name=status,enum=file.FileSystemError_FileSystemErrorStatus" json:"status,omitempty"`
	ErrorMessage string                                `protobuf:"bytes,2,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
}

func (m *FileSystemError) Reset()                    { *m = FileSystemError{} }
func (m *FileSystemError) String() string            { return proto.CompactTextString(m) }
func (*FileSystemError) ProtoMessage()               {}
func (*FileSystemError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FileSystemError) GetStatus() FileSystemError_FileSystemErrorStatus {
	if m != nil {
		return m.Status
	}
	return FileSystemError_ACCESS_DENIED
}

func (m *FileSystemError) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*FileSystemError)(nil), "file.FileSystemError")
	proto.RegisterEnum("file.FileSystemError_FileSystemErrorStatus", FileSystemError_FileSystemErrorStatus_name, FileSystemError_FileSystemErrorStatus_value)
}

func init() { proto.RegisterFile("errors.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x4a, 0x2b, 0x31,
	0x18, 0xbd, 0x99, 0x5b, 0x8b, 0xc6, 0x56, 0x63, 0x44, 0xac, 0xbb, 0x52, 0x37, 0x05, 0x61, 0x16,
	0xfa, 0x04, 0x69, 0x92, 0xd2, 0xc0, 0x74, 0x66, 0x48, 0xa2, 0x38, 0xab, 0x8f, 0x0a, 0x51, 0x0a,
	0xad, 0x23, 0x93, 0xb8, 0xf0, 0x31, 0xc4, 0x17, 0x96, 0xa4, 0xe2, 0xa2, 0xb8, 0xcc, 0xc9, 0xf9,
	0xfb, 0x0e, 0x1e, 0xb8, 0xae, 0x6b, 0x3b, 0x9f, 0xbf, 0x75, 0x6d, 0x68, 0x69, 0xef, 0x79, 0xbd,
	0x71, 0x93, 0xcf, 0x0c, 0x9f, 0xce, 0xd7, 0x1b, 0x67, 0x3e, 0x7c, 0x70, 0x5b, 0x19, 0x09, 0x94,
	0xe3, 0xbe, 0x0f, 0xab, 0xf0, 0xee, 0x47, 0x68, 0x8c, 0xa6, 0x27, 0xb7, 0x37, 0x79, 0xa4, 0xe6,
	0x7b, 0xb4, 0xfd, 0xb7, 0x49, 0x12, 0xfd, 0x23, 0xa5, 0xd7, 0x78, 0x98, 0xe2, 0x60, 0xeb, 0xbc,
	0x5f, 0xbd, 0xb8, 0x51, 0x36, 0x46, 0xd3, 0x23, 0xbd, 0xeb, 0xb0, 0xdc, 0x61, 0x93, 0x2f, 0x84,
	0x2f, 0xfe, 0xb4, 0xa1, 0x67, 0x78, 0xc8, 0x38, 0x97, 0xc6, 0x80, 0x90, 0xa5, 0x92, 0x82, 0xfc,
	0xa3, 0x97, 0xf8, 0x5c, 0x28, 0x2d, 0xb9, 0xad, 0x74, 0x03, 0x65, 0x65, 0x41, 0x2e, 0x6b, 0xdb,
	0x10, 0x14, 0x3f, 0xe6, 0xaa, 0x90, 0xc0, 0x0a, 0x2d, 0x99, 0x68, 0x40, 0x3e, 0x1a, 0x65, 0x0d,
	0xc9, 0x28, 0xc1, 0x03, 0x55, 0x3e, 0xb0, 0x42, 0x09, 0xa8, 0x99, 0x5d, 0x90, 0xff, 0x11, 0x29,
	0x2b, 0x30, 0xf7, 0x7c, 0x01, 0x51, 0x42, 0x7a, 0x31, 0x28, 0x7a, 0xfd, 0x3a, 0x93, 0x83, 0xd9,
	0x15, 0x3e, 0x7c, 0x75, 0x21, 0x1d, 0x3d, 0x3b, 0x4e, 0xa5, 0x7c, 0x1d, 0x27, 0xab, 0xd1, 0x53,
	0x3f, 0x6d, 0x77, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xae, 0x8e, 0x87, 0x4b, 0x01, 0x00,
	0x00,
}
